#!/usr/bin/env bash
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install -y neovim

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "export MYVIMRC='~/mflova-linux-setup/mflova-vim-config/cfg/init.vim'" >> ~/.bashrc
echo "export VIMINIT='source $MYVIMRC'" >> ~/.bashrc

echo "Open VIM, ignore the errors and execute :PluginInstall"


nvim -c PluginInstall
read -p "Go to the folder of the spotify plugin in bundle and execute 'do make'. Press [ENTER]"
read -p "Go to the folder of the sniprun plugin in bundle and execute 'bash install.sh'. Press [ENTER]"
read -p "Go to the folder of the markdown-preview.nvim plugin in bundle and execute 'cd app && yarn install'. Press [ENTER]"
read -p "Remember to install the Tresitter parsers (used for highlighting improved) with :TSUpdate and then :TSInstall filetype"
read -p "Execute command :UpdateRemotePlugins in vim." 
