#!/usr/bin/env bash
sudo apt-get install -y vim-nox silversearcher-ag
sudo apt install -y build-essential cmake vim-nox python3-dev
sudo apt install -y mono-complete golang nodejs default-jdk npm
sudo apt-get install -y exuberant-ctags
sudo apt-get install -y silversearcher-ag

pip install flake8
pip install doq
pip3 install doq

#git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Open VIM, ignore the errors and execute :PluginInstall"

cd ~/.vim/bundle/YouCompleteMe
python3 install.py --all
cd ~

echo "export VIMINIT='source $MYVIMRC'" >> ~/.bashrc
echo "export MYVIMRC='~/mflova-linux-setup/mflova-vim-config/cfg/.vimrc'" >> ~/.bashrc

echo "Installation finished, Just call :PluginInstall in VIM and restart it"
