- hosts: localhost
  tasks:
  - name: Generic LSP tools
    community.general.npm:
      name: vim-language-server
      path: /usr/bin/npm

  - name: Python related tools
    community.general.npm:
      name:
        - pyright
      path: /usr/bin/npm

  - name: Markdown related tools
    community.general.npm:
      name:
        - mdl
      path: /usr/bin/npm

  - name: Bash related tools
    community.general.npm:
      name:
        - bash-language-server
      path: /usr/bin/npm
    apt:
      name:
        - shellcheck

  - name: Install YAML LSP
    community.general.snap:
      name: yaml-language-server

  - name: Install YAML linters
    apt:
      name: yamllint
      update_cache: yes

  - name: Cmake related tools
    pip:
      name: 
        - cmake-language-server
        - cmakelint

  - name: C/C++ tools through pip
    pip:
      name: 
        - cpplint

  - name: C/C++ tools through apt
    apt:
      name:
        - ccls # LSP
        - clang-tidy
        - cppcheck

  - name: LUA related tools
    apt:
      name:
        - lua-check

  - name: RST related tools
    pip:
      name:
        - esbonio # LSP
        - rstcheck
        - restructuredtext-lint

  - name: Grammar-based tools
    pip:
      name:
        - codespell
        - proselint

  - name: Install python packages
    pip:
      name: 
        - pyright
        - python-language-server[all]
        - setuptools
        - pylsp-mypy
        - pylsp-rope
        - pandas-stubs
        - numpy
        - pytest


  - name: Install python tools
    pip:
      name: 
        - pydocstyle
        - pycodestyle
        - vulture
        - mypy
        - flake8
        - pydocstyle
        - pylint
        - doq
        - pytest
        - pytest-cov
        - dlint
        - pandas-vet
        - darglint
        - flake8-pytest-style
        - flake8-simplify
        - flake8-todo
        - flake
        - flake8-todo
        - flake8-bugbear
        - flake8-docstrings
        - flake8-comprehensions
        - flake8-commas
        - flake8-rst-docstrings
        - flake8-docstrings
        - flake8-markdown
        - flake8-builtins
        - flake8-broken-line
        - flake8-pie
        - flake8-mutable
        - flake8-deprecated
        - flake8-type-checking
        - flake8-typing-imports
        - flake8-requirements
        - flake8-implicit-str-concat
        - flake8-use-fstring
        - vim-vint
