- hosts: localhost
  become: yes
  tasks:

  - name: Download nvim 0.7.0
    get_url:
      url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb
      dest: /tmp

  - name: Install neovim
    apt:
      deb: /tmp/nvim-linux64.deb
      update_cache: yes

  - name: Install python
    apt:
      pkg:
        - python3-dev
        - python3-pip
      update_cache: yes

  - name: Install curl
    snap:
      name: curl

  - name: Install a list of packages
    apt:
      pkg:
      - xclip
      - build-essential
      - cmake
      - mono-complete
      - golang
      - nodejs
      - default-jdk
      - npm
      - universal-ctags
      - silversearcher-ag
      - isort
      - yapf3
      - python3-autopep8
      - ripgrep
      update_cache: yes

  - name: Install python packages
    pip:
      name: 
        - debugpy
        - pytest-xdist
        - ropevim
        - pynvim
        - https://github.com/Rykka/instant-rst.py/archive/master.zip

  - name: Install other snap packages
    snap:
      name:
        - spotify
        - gh

  - name: Create STUBSPATH variable
    shell: echo "export STUBSPATH=$HOME/stubs" >> ~/.bashrc
    become: no

  - name: Create MYPYPATH
    shell: echo "export MYPYPATH=\$STUBSPATH" >> ~/.bashrc
    become: no

  - name: Create MYVIMRC
    shell: echo "export MYVIMRC='{{playbook_dir}}/../cfg/init.vim'" >> ~/.bashrc
    become: no

  - name: Create VIMINIT
    shell: echo "export VIMINIT='source \$MYVIMRC'" >> ~/.bashrc
    become: no

  - shell: which python3
    register: python3_dir

  - name: Create PYTHON_DIR
    shell: echo "export PYTHON_DIR='{{python3_dir.stdout_lines[0]}}'" >> ~/.bashrc
    become: no

  - name: Create empty CPP_BUILD_DIR
    shell: echo "export CPP_BUILD_DIR=''" >> ~/.bashrc
    become: no
